### ISSUE TITLE
Number of days btw two YearlessDateField

### ISSUE THREAD

**Issue by denver28** [seddonym/django-yearlessdate#10]
Having two fields such as :
    date_from = models.YearlessDateField()
    date_to = models.YearlessDateField()
    no_of_days = models.CharField(max_length=50)
i would like to count the number of days btw the date_from and date_to

**Comment by seddonym** [comment]
It's not possible to say how many days are between any two yearless dates, unless you know the year too (because of leap years).

The easy way to do this is to convert the yearless dates into `datetime.date`s with the appropriate year - something like:

```
from datetime import date
date_1 = date(2019, yearless_date_1.month, yearless_date_1.day)
date_2 = date(2019, yearless_date_2.month, yearless_date_2.day)

days_between = (date_2 - date_1).days
```

Finally, if you're storing no_of_days in a model field, you're probably better off with an IntegerField.

Good luck!

**Comment by denver28** [comment]
Well thank you I found the solution
